site_name: HRI Teleoperation Tutorial
site_description: A tutorial on teleoperation for human-robot interaction
nav:
  - Home: index.md
  - Tutorials (Beginner): tutorial.md
  - Tutorials (Intermediate): tutorial_intermediate.md
theme:
  name: readthedocs