site_name: HRI Teleoperation Tutorial
site_description: A tutorial on teleoperation for human-robot interaction
site_url: https://sssa-teleoperation.github.io/teleoperation-docs/
nav:
  - Home: index.md
  - Tutorials (Beginner): tutorial.md
  - Tutorials (Intermediate): tutorial_intermediate.md
  - THE Architecture: the_architecture.md
  - Resources: resources.md

theme:
  name: material
  features:
    - content.code.copy

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
