site_name: HRI Teleoperation Tutorial
site_description: A tutorial on teleoperation for human-robot interaction
nav:
  - Home: index.md
  - Tutorials (Beginner): tutorial.md
  - Tutorials (Intermediate): tutorial_intermediate.md
  - Resources: resources.md

theme:
  name: readthedocs

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true