site_name: HRI Teleoperation Tutorial
site_description: A tutorial on teleoperation for human-robot interaction
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - WSL: wsl.md
theme:
  name: readthedocs